version: 2
snapshot:
  widths:
    - 375   # Mobile
    - 768   # Tablet
    - 1280  # Desktop
    - 1920  # Large desktop
  minHeight: 1024
  percyCSS: |
    /* Masquer les éléments dynamiques pour des snapshots cohérents */
    .currentTimeLine { display: none !important; }
    /* Masquer l'heure actuelle qui change */
    .currentTimeText { visibility: hidden !important; }
    /* Fixer les animations */
    * { 
      animation-duration: 0s !important; 
      transition-duration: 0s !important;
    }